# Generated by Django 5.2.7 on 2025-11-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50)),
                ('appointment_id', models.CharField(max_length=50)),
                ('tech_id', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('polling_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50)),
                ('appointment_id', models.CharField(max_length=50)),
                ('ready', models.BooleanField(default=False)),
                ('data', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
