# Generated by Django 5.2.7 on 2025-11-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_dispatchjob_historyjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchjob',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Dispatched', 'Dispatched'), ('Working', 'Working'), ('Done', 'Done')], default='Working', max_length=20),
            preserve_default=False,
        ),
    ]
