# Generated by Django 5.2.7 on 2025-11-07 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_dispatchjob_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchjob',
            name='recording_active',
            field=models.BooleanField(default=False, help_text="iOS has acknowledged server's 'Working' push notification"),
        ),
        migrations.AddField(
            model_name='dispatchjob',
            name='recording_stopped',
            field=models.BooleanField(default=False, help_text="iOS has acknowledged server's 'Done' push notification"),
        ),
        migrations.AlterField(
            model_name='dispatchjob',
            name='polling_active',
            field=models.BooleanField(default=True, help_text="Server is polling ST for 'Working' status"),
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
