# Generated by Django 5.2.7 on 2025-11-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_dispatchjob_recording_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchjob',
            name='notified_done',
            field=models.BooleanField(default=False, help_text='Push sent for status=Done (result:2)'),
        ),
        migrations.AddField(
            model_name='dispatchjob',
            name='notified_history',
            field=models.BooleanField(default=False, help_text='Push sent for history ready (result:3)'),
        ),
        migrations.AddField(
            model_name='dispatchjob',
            name='notified_working',
            field=models.BooleanField(default=False, help_text='Push sent for status=Working (result:1)'),
        ),
    ]
