# Generated by Django 5.2.7 on 2025-11-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_dispatchjob_notified_done_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchjob',
            name='ai_document_built',
            field=models.BooleanField(default=False, help_text='AI document has been built and uploaded to S3'),
        ),
        migrations.AddField(
            model_name='dispatchjob',
            name='ai_document_url',
            field=models.TextField(blank=True, help_text='S3 URL for AI job data document', null=True),
        ),
    ]
