# Generated by Django 5.2.7 on 2025-11-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_dispatchjob_ai_document_built_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchjob',
            name='ai_document_url',
        ),
        migrations.AddField(
            model_name='dispatchjob',
            name='ai_document_s3_key',
            field=models.TextField(blank=True, help_text='S3 key for AI job data document', null=True),
        ),
    ]
