# Generated by Django 5.2.7 on 2025-11-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0007_remove_dispatchjob_ai_document_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatchjob',
            name='out_of_order',
            field=models.BooleanField(default=False, help_text="Appointment returned to 'Scheduled' status after Dispatch"),
        ),
    ]
