# Generated by Django 5.2.7 on 2025-11-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_dispatchjob_out_of_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryJob',
        ),
    ]
