# Generated by Django 5.2.8 on 2026-02-05 19:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0009_delete_historyjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTitanCallSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session_metadata', models.JSONField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('downloading', 'Downloading'), ('transcribing', 'Transcribing'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('full_transcript', models.TextField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ServiceTitan Call Session',
                'verbose_name_plural': 'ServiceTitan Call Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('tone', models.CharField(blank=True, max_length=50, null=True)),
                ('importance', models.CharField(blank=True, max_length=50, null=True)),
                ('full_ai_response', models.TextField(blank=True, null=True)),
                ('structured_analysis', models.JSONField(blank=True, null=True)),
                ('analysis_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='history.servicetitancallsession')),
            ],
            options={
                'verbose_name': 'Call Analysis',
                'verbose_name_plural': 'Call Analyses',
            },
        ),
        migrations.CreateModel(
            name='CallAudioChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('audio_file', models.FileField(upload_to='call_recordings/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('transcribed', 'Transcribed'), ('error', 'Error')], default='uploaded', max_length=20)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('speaker_segments', models.JSONField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='history.servicetitancallsession')),
            ],
            options={
                'verbose_name': 'Call Audio Chunk',
                'verbose_name_plural': 'Call Audio Chunks',
                'ordering': ['session', 'chunk_order'],
                'unique_together': {('session', 'chunk_order')},
            },
        ),
    ]
