# Generated by Django 5.2.7 on 2025-10-30 19:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkedConversation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('chunks_folder_path', models.CharField(blank=True, max_length=500)),
                ('chunk_count', models.IntegerField(default=0)),
                ('received_chunks', models.JSONField(default=list)),
                ('last_preliminary_transcription', models.DateTimeField(blank=True, null=True)),
                ('final_audio_url', models.URLField(blank=True)),
                ('audio_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('is_chunks_complete', models.BooleanField(default=False)),
                ('is_final_uploaded', models.BooleanField(default=False)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('full_transcript', models.TextField(blank=True)),
                ('preliminary_transcript', models.TextField(blank=True)),
                ('save_permanently', models.BooleanField(default=False)),
                ('scheduled_deletion_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chunked Conversation',
                'verbose_name_plural': 'Chunked Conversations',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_label', models.CharField(max_length=50)),
                ('identified_name', models.CharField(blank=True, max_length=255)),
                ('is_recording_user', models.BooleanField(default=False)),
                ('name_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='chunking.chunkedconversation')),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'ordering': ['speaker_label'],
                'unique_together': {('conversation', 'speaker_label')},
            },
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='chunking.chunkedconversation')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='chunking.speaker')),
            ],
            options={
                'verbose_name': 'Transcript Segment',
                'verbose_name_plural': 'Transcript Segments',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='AudioChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.IntegerField()),
                ('start_time_seconds', models.IntegerField()),
                ('duration_seconds', models.IntegerField()),
                ('s3_chunk_url', models.URLField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('transcript_text', models.TextField(blank=True)),
                ('transcript_source', models.CharField(choices=[('preliminary', 'Preliminary (Fast)'), ('final', 'Final (High Quality)')], default='preliminary', max_length=20)),
                ('transcribed_at', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('rms_level', models.FloatField(blank=True, null=True)),
                ('peak_amplitude', models.FloatField(blank=True, null=True)),
                ('speech_percentage', models.FloatField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chunking.chunkedconversation')),
            ],
            options={
                'verbose_name': 'Audio Chunk',
                'verbose_name_plural': 'Audio Chunks',
                'ordering': ['chunk_number'],
                'unique_together': {('conversation', 'chunk_number')},
            },
        ),
    ]
