# Generated by Django 5.2.7 on 2025-10-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedconversation',
            name='action_items',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chunkedconversation',
            name='analysis_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chunkedconversation',
            name='coaching_feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chunkedconversation',
            name='key_topics',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chunkedconversation',
            name='sentiment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='chunkedconversation',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chunkedconversation',
            name='transcription_error',
            field=models.TextField(blank=True),
        ),
    ]
