# Generated by Django 5.2.7 on 2025-11-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0002_chunkedconversation_action_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedconversation',
            name='final_audio_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
