# Generated by Django 5.2.7 on 2025-11-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0003_alter_chunkedconversation_final_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedconversation',
            name='multipart_parts',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chunkedconversation',
            name='multipart_s3_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='chunkedconversation',
            name='multipart_upload_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
