# Generated by Django 5.2.7 on 2025-11-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0004_chunkedconversation_multipart_parts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedconversation',
            name='formatted_transcript',
            field=models.TextField(blank=True),
        ),
    ]
