# Generated by Django 5.2.7 on 2025-11-03 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0005_chunkedconversation_formatted_transcript'),
        ('streaming', '0005_analysisprompt_is_default_analysisprompt_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedconversation',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chunkedconversation',
            name='prompt_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunked_conversations', to='streaming.analysisprompt'),
        ),
    ]
