# Generated by Django 5.2.7 on 2025-11-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0006_chunkedconversation_is_shared_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedconversation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chunkedconversation',
            name='job_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
