# Generated by Django 5.2.7 on 2025-11-13 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0007_chunkedconversation_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedconversation',
            name='is_transcribing',
            field=models.BooleanField(default=False),
        ),
    ]
