# Generated by Django 5.2.7 on 2025-12-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0008_chunkedconversation_is_transcribing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiochunk',
            options={'ordering': ['-conversation__started_at', 'chunk_number'], 'verbose_name': 'Audio Chunk', 'verbose_name_plural': 'Audio Chunks'},
        ),
        migrations.AddField(
            model_name='chunkedconversation',
            name='speakers_expected',
            field=models.IntegerField(default=2),
        ),
    ]
