# Generated by Django 5.2.8 on 2026-01-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0009_alter_audiochunk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunkedconversation',
            name='transcription_service_preference',
            field=models.CharField(choices=[('assemblyai', 'AssemblyAI'), ('whisper', 'OpenAI Whisper'), ('both', 'Both (Compare)')], default='both', help_text='Which transcription to use for analysis', max_length=20),
        ),
        migrations.AddField(
            model_name='chunkedconversation',
            name='whisper_formatted_transcript',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chunkedconversation',
            name='whisper_transcript',
            field=models.TextField(blank=True),
        ),
    ]
