# Generated by Django 5.2.7 on 2026-05-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0010_add_whisper_transcript_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunkedconversation',
            name='transcription_service_preference',
            field=models.CharField(choices=[('assemblyai', 'AssemblyAI'), ('whisper', 'OpenAI Whisper'), ('both', 'Both (Compare)')], default='assemblyai', help_text="Which transcription to run. 'both' adds a Whisper comparison pass; analysis still uses the AssemblyAI transcript.", max_length=20),
        ),
    ]
