# Generated by Django 5.2.7 on 2025-10-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_conversation_audio_delete_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='audio_quality',
            field=models.CharField(choices=[('streaming_only', 'Streaming Only (16kHz)'), ('high_quality', 'High Quality (44.1kHz)')], default='streaming_only', max_length=20),
        ),
        migrations.AddField(
            model_name='conversation',
            name='streaming_audio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='transcriptsegment',
            name='source',
            field=models.CharField(choices=[('streaming', 'Streaming Transcription'), ('high_quality', 'High Quality Transcription')], default='streaming', max_length=20),
        ),
    ]
