# Generated by Django 5.2.7 on 2025-10-28 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_conversation_audio_quality_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationanalysis',
            name='shared_with_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AnalysisPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('plain_text', models.TextField(help_text='What you want the AI to analyze, in plain English')),
                ('optimized_prompt', models.TextField(help_text='AI-optimized professional prompt')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversationanalysis',
            name='prompt_used',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='streaming.analysisprompt'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='streaming.analysisprompt'),
        ),
    ]
