# Generated by Django 5.2.7 on 2025-10-29 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_conversationanalysis_shared_with_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisprompt',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Default prompt used when user has no assignment'),
        ),
        migrations.AddField(
            model_name='analysisprompt',
            name='is_system',
            field=models.BooleanField(default=False, help_text='System prompt that cannot be edited or deleted'),
        ),
    ]
