# Generated by Django 5.2.7 on 2025-11-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0005_analysisprompt_is_default_analysisprompt_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auto_share',
            field=models.BooleanField(default=False, help_text='Automatically share all conversations with admin'),
        ),
    ]
