# Generated by Django 5.2.7 on 2025-11-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_userprofile_auto_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='st_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
