# Generated by Django 5.2.7 on 2025-11-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0007_userprofile_st_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationanalysis',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='speaker',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='transcriptsegment',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationanalysis',
            name='prompt_used',
        ),
        migrations.AlterUniqueTogether(
            name='speaker',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='transcriptsegment',
            name='speaker',
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='ConversationAnalysis',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
        migrations.DeleteModel(
            name='TranscriptSegment',
        ),
    ]
